version: "2"
run:
  concurrency: 4
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 50

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - errorlint
    - nilerr
    - gocritic
    - revive
    - misspell
    - gosec
    - bodyclose
    - noctx
    - containedctx

  settings:
    errcheck:
      check-type-assertions: true
    revive:
      rules:
        - name: exported
          severity: warning

formatters:
  enable:
    - gofumpt
    - goimports
